In [5]:
import numpy as np
one_dim = np.array([1,2,3,4,5])
one_dim


array([1, 2, 3, 4, 5])

In [6]:
one_dim[0:3]

array([1, 2, 3])

In [7]:
np.delete(one_dim,(1),axis=0)

array([1, 3, 4, 5])

In [8]:
one_dim=np.arange(1,10,2)

In [9]:
one_dim

array([1, 3, 5, 7, 9])

In [71]:
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
two_dim[1:3,1:2]

ValueError: could not broadcast input array from shape (2,) into shape (2,1)

In [74]:
# two_dim=np.delete(two_dim,(0,1),axis=0)

In [75]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.delete(two_dim,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [82]:
two_dim=np.arange(0,12).reshape(3,4)

In [83]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.random.randint(1,10,100)

array([4, 4, 7, 6, 4, 9, 5, 1, 9, 1, 6, 6, 8, 3, 9, 2, 7, 1, 8, 7, 9, 1,
       5, 2, 5, 8, 6, 6, 7, 8, 9, 5, 3, 9, 1, 1, 5, 1, 5, 2, 3, 8, 9, 3,
       1, 4, 6, 2, 9, 2, 6, 8, 4, 3, 5, 5, 1, 9, 4, 6, 6, 1, 2, 8, 9, 2,
       8, 5, 3, 5, 8, 3, 5, 5, 2, 9, 4, 5, 1, 8, 1, 9, 5, 4, 8, 7, 7, 4,
       4, 8, 7, 1, 8, 8, 3, 2, 9, 4, 5, 4])

In [85]:
 two_ran=np.random.randint(0,110,12).reshape(3,4)

In [87]:
two_ran

array([[ 16,  90,  39,  31],
       [ 76,  65,  82, 105],
       [ 80,  39,  46,  62]])

In [93]:
n=np.random.rand(16).reshape(4,4)

In [94]:
np.linalg.inv(n)

array([[ 0.75265312,  0.94565682,  0.17606998, -2.04226776],
       [ 0.04041368, -0.0760898 , -1.46729171,  2.08749643],
       [ 1.09381521, -0.63812088,  1.1380737 , -1.07457276],
       [-1.13657259,  0.39867427,  0.88155015,  0.36160205]])

In [97]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [98]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [99]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
a=np.array([[1,2],[3,4]])

In [101]:
b=np.array([[5,6],[7,8]])

In [102]:
a@b

array([[19, 22],
       [43, 50]])

In [103]:
a+b

array([[ 6,  8],
       [10, 12]])

# three dimension

In [ ]:
three_dim=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
three_dim[0,1,2]

In [ ]:
np.delete(three_dim,0,axis=2)